"""change table user alter password to password_hash

Revision ID: d7fd99319024
Revises: b494474e0090
Create Date: 2017-03-29 14:59:13.510611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7fd99319024'
down_revision = 'b494474e0090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venus_exam', 'paper_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'venus_exam', 'venus_paper', ['paper_id'], ['id'])
    op.add_column('venus_user', sa.Column('password_hash', sa.String(length=500), nullable=False))
    op.drop_column('venus_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venus_user', sa.Column('password', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('venus_user', 'password_hash')
    op.drop_constraint(None, 'venus_exam', type_='foreignkey')
    op.alter_column('venus_exam', 'paper_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
